### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by rajeevyen** [krishnaik06/Chicken-Disease-Classification-Projects#1]
[2023-06-24 22:51:15,945: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-24 22:51:15,947: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-24 22:51:15,948: INFO: common: created directory at: artifacts]
[2023-06-24 22:51:15,949: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2023-06-24 22:51:15,949: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 16
     11     training.train(
     12         callback_list=callback_list
     13     )
     15 except Exception as e:
---> 16     raise e

Cell In[15], line 5
      3 prepare_callbacks_config = config.get_prepare_callback_config()
      4 prepare_callbacks = PrepareCallback(config=prepare_callbacks_config)
----> 5 callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
      7 training_config = config.get_training_config()
      8 training = Training(config=training_config)

Cell In[9], line 28, in PrepareCallback.get_tb_ckpt_callbacks(self)
     25 def get_tb_ckpt_callbacks(self):
     26     return [
     27         self._create_tb_callbacks,
---> 28         self._create_ckpt_callbacks
     29     ]

Cell In[9], line 19, in PrepareCallback._create_ckpt_callbacks(self)
     17 @property
...
   1377     if options is None or isinstance(
   1378         options, tf.saved_model.SaveOptions
   1379     ):

AttributeError: 'PosixPath' object has no attribute 'endswith'

Getting error at the time of creating training folders.

**Comment by rajeevyen** [comment]
Issue got resolved after changing _create_ckpt_callback method to below code snippet

@property
    def _create_ckpt_callbacks(self):
        filepath_str = str(self.config.checkpoint_model_filepath)  # Convert PosixPath to string
        return tf.keras.callbacks.ModelCheckpoint(
            filepath=filepath_str,
            save_best_only=True
        )

**Comment by dcepeda31415** [comment]
Sir you are a savior. I thank you so much
